name: ci
on:
  push:
  pull_request:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install -U pip
      - run: pip install -r requirements-dev.txt
      - run: pre-commit run --all-files
      - name: Verify required files
        run: |
          test -f index.html
          test -f CNAME
