name: link-check
on:
  push:
  pull_request:
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --accept 429,403 --exclude-mail '^mailto:'
